export const User = [
  {
    id: 1,
    first_name: 'channaveer',
    last_name: 'patil',
    email: 'channaveerpatil999@gmail.com',
    gender: 'male',
  },
  {
    id: 2,
    first_name: 'mangesh',
    last_name: 'landge',
    email: 'mangesh102@gmail.com',
    gender: 'male',
  },
  {
    id: 3,
    first_name: 'vinod',
    last_name: 'reddy',
    email: 'vinod420@gmail.com',
    gender: 'male',
  },
  {
    id: 4,
    first_name: 'raju',
    last_name: 'reddy',
    email: 'raju429@gmail.com',
    gender: 'male',
  },
  {
    id: 5,
    first_name: 'santoshi',
    last_name: 'malge',
    email: 'snatoshimalge510@gmail.com',
    gender: 'female',
  },
  {
    id: 6,
    first_name: 'anuradha',
    last_name: 'malge',
    email: 'anuradha510@gmail.com',
    gender: 'female',
  },
  {
    id: 7,
    first_name: 'pooja',
    last_name: 'patil',
    email: 'pooja120@gmail.com',
    gender: 'female',
  },
  {
    id: 8,
    first_name: 'priyanka',
    last_name: 'patil',
    email: 'priyanka789@gmail.com',
    gender: 'female',
  },
  {
    id: 9,
    first_name: 'chaitra',
    last_name: 'ambalgi',
    email: 'chaita560@gmail.com',
    gender: 'female',
  },
  {
    id: 10,
    first_name: 'sam',
    last_name: 'sundar',
    email: 'sam230@gmail.com',
    gender: 'male',
  },
];
